global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # - job_name: 'tempo'
  #   static_configs:
  #     - targets: ['tempo:3200']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'go-app'
    scrape_interval: 15s
    static_configs:
      - targets: ['go-app:2112']
